name: Build and Push Mihomo Docker Image

on:
  schedule:
    # 每天 UTC 时间 0 点自动检查更新
    - cron: '0 0 * * *'
  # 允许手动触发构建
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Latest Version
        id: get_version
        run: |
          LATEST_VERSION=$(curl -sL https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.tag_name')
          echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mihomo-auto:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mihomo-auto:${{ steps.get_version.outputs.latest_version }}
